### ISSUE TITLE
Bridge-server crashing due to TypeError

### ISSUE THREAD

**Issue by fgiorgetti** [skupperproject/skupper#139]
```
2020-07-24T18:22:58.735Z bridge-server info ignoring watch event for bridge-server (does not match ..data)
2020-07-24T18:22:58.736Z bridge-server info ignoring watch event for ..2020_07_22_13_28_47.560349582 (does not match ..data)
2020-07-24T18:22:59.144Z bridge-server info http://details/details/0: 404
2020-07-24T18:22:59.145Z bridge-server info server sending reply for request to http://details/details/0: {"to":"amqp:/_topo/0/aws-eu-west-skupper-router-9795f464f-z756w/temp.CzyYa+ws4dq6qBt","correlation_id":30095,"subject":"404","application_properties":{"x-powered-by":"Servlet/3.1","allow":"GET,OPTIONS,HEAD","date":"Fri, 24 Jul 2020 18:22:57 GMT","content-length":"0","content-language":"en-US","connection":"Close"},"group_id":"198b358f-9bca-4ffb-ad30-e809301039c5"}
/opt/app-root/lib/bridges.js:91
            metrics.http_egress_request(self.metrics, self.host, options.method, response.statusCode, site, context.message.body ? context.message.body.length : 0, message_out.body.length, elapsed(start));
                                                                                                                                                                                     ^

TypeError: Cannot read property 'length' of undefined
    at IncomingMessage.<anonymous> (/opt/app-root/lib/bridges.js:91:182)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by grs** [comment]
What image for the bridge-server did you see this with? (It *should* already be fixed in quay.io/skupper/bridge-server latest/0.3/0.3.0)

**Comment by fgiorgetti** [comment]
Issue has been resolved in skupper-proxy.
