### ISSUE TITLE
bridge-server (icproxy) will crash when exposing http2 servies

### ISSUE THREAD

**Issue by admirito** [skupperproject/skupper#285]
I have installed the skupper `0.3.2` and everything works fine. I have a deployment `foo` and a related service with the same name `foo` that uses grpc i.e. `http2` (without ssl).
If I issue an expose on the `service` with `--protocol=http2` the `bridge-server` container in `skupper-router` pod will crash with the following log:

```sh
skupper expose service foo --protocol http2 --address skupper-foo
```
```
(...) lots of  connection closed / connection error logs here; curiously it is the wrong IP address 
      with the wrong port number. 50060 is the port number for the `foo` service but `10.233.82.112` and
      `10.233.82.131` etc below are the endpoint address of my other services on other ports! (...)
2020-10-07T12:24:44.663Z bridge-server info http2 connection closed; reconnecting                                                                                                                                   
2020-10-07T12:24:44.664Z bridge-server info http2 connection error: Error: connect ECONNREFUSED 10.233.82.112:50060                                                                                                 
2020-10-07T12:24:44.664Z bridge-server info http2 connection closed; reconnecting                                                                                                                                   
2020-10-07T12:24:44.665Z bridge-server info http2 connection error: Error: connect ECONNREFUSED 10.233.82.131:50060                                                                                                 
2020-10-07T12:24:44.665Z bridge-server info http2 connection closed; reconnecting                                                                                                                                   
2020-10-07T12:24:44.665Z bridge-server info http2 connection error: Error: connect ECONNREFUSED 10.233.82.116:50060                                                                                                 
2020-10-07T12:24:44.666Z bridge-server info http2 connection closed; reconnecting                                                                                                                                   
2020-10-07T12:24:44.666Z bridge-server info http2 connection error: Error: connect ECONNREFUSED 10.233.82.160:50060                                                                                                 
2020-10-07T12:24:44.666Z bridge-server info http2 connection closed; reconnecting

events.js:174
      throw er; // Unhandled 'error' event
      ^
Error: No route to the destination node
    at Sender.link.on_detach (/opt/app-root/node_modules/rhea/lib/link.js:165:86)
    at Session.on_detach (/opt/app-root/node_modules/rhea/lib/session.js:730:27)
    at Connection.(anonymous function) [as on_detach] (/opt/app-root/node_modules/rhea/lib/connection.js:809:30)
    at c.dispatch (/opt/app-root/node_modules/rhea/lib/types.js:910:33)
    at Transport.read (/opt/app-root/node_modules/rhea/lib/transport.js:109:36)
    at SaslClient.read (/opt/app-root/node_modules/rhea/lib/sasl.js:328:26)
    at Connection.input (/opt/app-root/node_modules/rhea/lib/connection.js:543:35)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
Emitted 'error' event at:
    at Container.dispatch (/opt/app-root/node_modules/rhea/lib/container.js:41:33)
    at Connection.dispatch (/opt/app-root/node_modules/rhea/lib/connection.js:261:40)
    at Connection.input (/opt/app-root/node_modules/rhea/lib/connection.js:561:18)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

It is worth mentioning that exposing the service with `tcp` protocol works fine:

 ```sh
skupper expose service foo --protocol tcp --address skupper-foo
```

More strangely exposing the `deployment` with `--protocol=http2`  will work fine, too:

```sh
skupper expose deployment foo --protocol http2 --port 50060 --address skupper-foo
```

Unfurtenatly, I coudn't find any documentation regarding the expsoing of the `service`. The [docs](https://skupper.io/start/index.html#step-5-expose-your-services) only has an example with exposing the `deployment`. Are there any differences between exposing a `service` and a `deployment`? As I have already defined a service for my deployment, I prefer using the `service` for exposing by skupper.

**Comment by grs** [comment]
The expose run against a service modifies that service, whereas the expose against the deployment just causes a service to be created through which the pods of the deployment can be accessed. That is why I think exposing the deployment is 'nicer' (at least in my view).

That said, exposing the service should work. (And the bridge-server should not crash!). Not sure what exactly is going on. Would you be able to create a simple reproducer?

**Comment by admirito** [comment]
It is a little strange for me. If exposing service modifies that service, why `--address` argument is required for `skupper expose service` command:

```sh
$ skupper expose service foo

Error: --address option is required for target type 'service'
```

And, with `--address` it is obvious that skupper will create a new service (although it doesn't rule out the modification of the original service, I still think it is not a necessity) and just out if curiosity do you know what will happen if you expose the service with the same name as the original service? I think I did it once and it worked :smile: 

But about the reproducer, [yages](https://github.com/mhausenblas/yages) seems like a good option for testing. Unfortunately, their [app.yaml](http://mhausenblas.info/yages/app.yaml) will not work with the latest versions of kuberntes but you can use the following manifests:

```yaml
$ cat yages.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: yages
  name: yages
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yages
  template:
    metadata:
      labels:
        app: yages
    spec:
      containers:
      - name: grpcsrv
        image: quay.io/mhausenblas/yages:0.1.0
        ports:
        - containerPort: 9000
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: yages
  name: yages
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: yages


$ kubectl apply -f yages.yaml
```

And then after setting up the skupper and connect `east` and `west` clusters:

```
$ skupper expose deployment yages --protocol http2 --port 9000 --address skupper-yages-deploy
$ skupper expose service yages --address skupper-yages-svc
$ skupper expose service yages --protocol tcp --address skupper-yages-svc-tcp
$ skupper expose service yages --protocol http2 --address skupper-yages-svc-http2
```

Now on the other cluster:

```
$ kubectl run -it --rm grpcurl --restart=Never --image=quay.io/mhausenblas/gump:0.1 -- sh

/go $ grpcurl --plaintext skupper-yages-deploy:9000 yages.Echo.Ping
{
  "text": "pong"
}

/go $ grpcurl --plaintext skupper-yages-svc:9000 yages.Echo.Ping
Error invoking method "yages.Echo.Ping": failed to query for service descriptor "yages.Echo": rpc error: code = Unavailable desc = transport is closing

/go $ grpcurl --plaintext skupper-yages-svc-tcp:9000 yages.Echo.Ping
Error invoking method "yages.Echo.Ping": failed to query for service descriptor "yages.Echo": rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: <nil>

/go $ grpcurl --plaintext skupper-yages-svc-http2:9000 yages.Echo.Ping
====> this command will cause crashing the bridge-server container <====
```

The above test will show that exposing the `service` for a service on `http2` will not work at all. If you expose it via `--protocol tcp` or without `--protocol` it will simply not work (grpc `Error: invoking method` above) and with `--protocol http2` it will cause the `bridge-server` (on the remote cluster which hosts the deployment)  to crash.

**Comment by grs** [comment]
Thanks for the reproducer I will look into that shortly!

You are right, the expose command will indeed create a new service which targets the original (whereas if you simply annotate the original service that will be modified). Apologies for the inaccurate response.

**Comment by ajssmith** [comment]
Protocol adaptors have been moved from external proxies and are integrated with the qdr. Please, re-open an issue if problem experienced with release 0.5.0 or greater.
