### ISSUE TITLE
Incompatibility with golang 1.18.3

### ISSUE THREAD

**Issue by nluaces** [skupperproject/skupper#799]
The generation of tokens fails when compiling skupper with golang 1.18.3

```
unexpected fault address 0x0
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x46229f]
 
goroutine 1 [running]:
runtime.throw({0x13c0c11?, 0x40beb3?})
        /usr/lib/golang/src/runtime/panic.go:992 +0x71 fp=0xc000147628 sp=0xc0001475f8 pc=0x435b51
runtime.sigpanic()
        /usr/lib/golang/src/runtime/signal_unix.go:825 +0x305 fp=0xc000147678 sp=0xc000147628 pc=0x44afc5
aeshashbody()
        /usr/lib/golang/src/runtime/asm_amd64.s:1343 +0x39f fp=0xc000147680 sp=0xc000147678 pc=0x46229f
runtime.mapiternext(0xc00046c500)
        /usr/lib/golang/src/runtime/map.go:934 +0x2cb fp=0xc0001476f0 sp=0xc000147680 pc=0x41170b
runtime.mapiterinit(0xdae862?, 0xc000486760?, 0x7f5de04ad3e0?)
        /usr/lib/golang/src/runtime/map.go:861 +0x228 fp=0xc000147710 sp=0xc0001476f0 pc=0x4113e8
reflect.mapiterinit(0xdc2876?, 0xc0001477a8?, 0xc00046c500?)
        /usr/lib/golang/src/runtime/map.go:1373 +0x19 fp=0xc000147738 sp=0xc000147710 pc=0x45f139
github.com/modern-go/reflect2.(*UnsafeMapType).UnsafeIterate(...)
        /home/nluaces/go/pkg/mod/github.com/modern-go/reflect2@v1.0.1/unsafe_map.go:112
github.com/json-iterator/go.(*sortKeysMapEncoder).IsEmpty(0x11?, 0xc000147830?)
        /home/nluaces/go/pkg/mod/github.com/json-iterator/go@v1.1.8/reflect_map.go:329 +0x28 fp=0xc000147778 sp=0xc000147738 pc=0xdb60a8
github.com/json-iterator/go.(*placeholderEncoder).IsEmpty(0xb9f80?, 0xc000422d98?)
        /home/nluaces/go/pkg/mod/github.com/json-iterator/go@v1.1.8/reflect.go:336 +0x22 fp=0xc000147798 sp=0xc000147778 pc=0xdae8c2
github.com/json-iterator/go.(*structFieldEncoder).IsEmpty(0xc0004598c0, 0x125d497?)
        /home/nluaces/go/pkg/mod/github.com/json-iterator/go@v1.1.8/reflect_struct_encoder.go:118 +0x42 fp=0xc0001477b8 sp=0xc000147798 pc=0xdc2a22
github.com/json-iterator/go.(*structEncoder).Encode(0xc000459a10, 0xdc4687?, 0xc000422d80)
        /home/nluaces/go/pkg/mod/github.com/json-iterator/go@v1.1.8/reflect_struct_encoder.go:148 +0x55f fp=0xc000147890 sp=0xc0001477b8 pc=0xdc307f
github.com/json-iterator/go.(*structFieldEncoder).Encode(0xc000459c80, 0x1226500?, 0xc000422d80)
        /home/nluaces/go/pkg/mod/github.com/json-iterator/go@v1.1.8/reflect_struct_encoder.go:110 +0x56 fp=0xc000147908 sp=0xc000147890 pc=0xdc2876
github.com/json-iterator/go.(*structEncoder).Encode(0xc000459e30, 0x0?, 0xc000422d80)
        /home/nluaces/go/pkg/mod/github.com/json-iterator/go@v1.1.8/reflect_struct_encoder.go:158 +0x652 fp=0xc0001479e0 sp=0xc000147908 pc=0xdc3172
github.com/json-iterator/go.(*OptionalEncoder).Encode(0xc0002143c0?, 0x0?, 0x0?)
        /home/nluaces/go/pkg/mod/github.com/json-iterator/go@v1.1.8/reflect_optional.go:74 +0xa4 fp=0xc000147a30 sp=0xc0001479e0 pc=0xdba8a4
github.com/json-iterator/go.(*onePtrEncoder).Encode(0xc00013f840, 0xc00032edc0, 0xc0003668d0?)
        /home/nluaces/go/pkg/mod/github.com/json-iterator/go@v1.1.8/reflect.go:219 +0x82 fp=0xc000147a68 sp=0xc000147a30 pc=0xdade22
github.com/json-iterator/go.(*Stream).WriteVal(0xc000422d80, {0x13a9980, 0xc00032edc0})
        /home/nluaces/go/pkg/mod/github.com/json-iterator/go@v1.1.8/reflect.go:98 +0x158 fp=0xc000147ad8 sp=0xc000147a68 pc=0xdad138
github.com/json-iterator/go.(*frozenConfig).Marshal(0xc0002143c0, {0x13a9980, 0xc00032edc0})
        /home/nluaces/go/pkg/mod/github.com/json-iterator/go@v1.1.8/config.go:299 +0xc9 fp=0xc000147b70 sp=0xc000147ad8 pc=0xda43e9
k8s.io/apimachinery/pkg/runtime/serializer/json.(*Serializer).doEncode(0x1b6?, {0x15b6878?, 0xc00032edc0?}, {0x15b2b00, 0xc000692060})
        /home/nluaces/go/pkg/mod/k8s.io/apimachinery@v0.17.0/pkg/runtime/serializer/json/json.go:305 +0x6d fp=0xc000147c08 sp=0xc000147b70 pc=0xe0128d
k8s.io/apimachinery/pkg/runtime/serializer/json.(*Serializer).Encode(0xc00027c3c0, {0x15b6878, 0xc00032edc0}, {0x15b2b00, 0xc000692060})
        /home/nluaces/go/pkg/mod/k8s.io/apimachinery@v0.17.0/pkg/runtime/serializer/json/json.go:300 +0xfc fp=0xc000147c68 sp=0xc000147c08 pc=0xe011bc
github.com/skupperproject/skupper/client.(*VanClient).TokenClaimCreateFile(0xc0003c1280, {0x15c3ee0, 0xc0000400c8}, {0x0, 0x0}, {0xc0006a4090, 0x18, 0x18}, 0xc000233e00?, 0x2, ...)
        /home/nluaces/workspace/skupper/client/token_claim_create.go:78 +0x1fc fp=0xc000147d40 sp=0xc000147c68 pc=0x114cd5c
main.NewCmdTokenCreate.func1(0xc000427080?, {0xc000414db0, 0x1, 0x3?})
        /home/nluaces/workspace/skupper/cmd/skupper/skupper_token.go:60 +0x246 fp=0xc000147dd8 sp=0xc000147d40 pc=0x1162a26
github.com/spf13/cobra.(*Command).execute(0xc000427080, {0xc000414d20, 0x3, 0x3})
        /home/nluaces/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:840 +0x67c fp=0xc000147eb0 sp=0xc000147dd8 pc=0xec60bc
github.com/spf13/cobra.(*Command).ExecuteC(0xc00042a000)
        /home/nluaces/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:945 +0x37c fp=0xc000147f68 sp=0xc000147eb0 pc=0xec667c
github.com/spf13/cobra.(*Command).Execute(...)
        /home/nluaces/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:885
main.main()
        /home/nluaces/workspace/skupper/cmd/skupper/skupper.go:1914 +0x25 fp=0xc000147f80 sp=0xc000147f68 pc=0x115e725
runtime.main()
        /usr/lib/golang/src/runtime/proc.go:250 +0x212 fp=0xc000147fe0 sp=0xc000147f80 pc=0x438272
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc000147fe8 sp=0xc000147fe0 pc=0x464ea1
```

Compare and review the skupper executable built with 1.18 and previous versions.

**Comment by risentveber** [comment]
I've faced with the same issue in a different project. The solution is to update `github.com/modern-go/reflect2` to `v1.0.2` https://github.com/modern-go/reflect2/issues/24

**Comment by nluaces** [comment]
@risentveber thank you!
