### ISSUE TITLE
 enum vflow_attribute VFLOW_ATTRIBUTE_STREAM_ID (47) added to skupper-router, but not to skupper

### ISSUE THREAD

**Issue by hash-d** [skupperproject/skupper#980]
The change was done on skupper-router [a0313e54262abce2ec3a5a74aea9910294f16f10](https://github.com/skupperproject/skupper-router/commit/a0313e54262abce2ec3a5a74aea9910294f16f10) for its [#862](https://github.com/skupperproject/skupper-router/issues/862).

The actual use of that enum is more recent, on [#866](https://github.com/skupperproject/skupper-router/pull/866/files).

It causes skupper tests to fail on the CI (see [this build](https://app.circleci.com/pipelines/github/skupperproject/skupper/2038/workflows/662a9f4a-ca9f-40c3-ab59-63451bd9b608) and its [full logs](https://circleci.com/api/v1.1/project/github/skupperproject/skupper/10545/output/124/0?file=true&allocation-id=63ab5064eeb1af54d4cc99a8-0-build%2FS6XYWP9S))

**Comment by hash-d** [comment]
@ajssmith FYI

**Comment by hash-d** [comment]
```
KUBECONFIG=/home/circleci/.kube/config kubectl -n  public-examples-1 logs skupper-service-controller-78c67cd766-t6l4q -c vflow-collector -p --tail=2000 --timestamps
2022-12-27T20:16:18.134015562Z 2022/12/27 20:16:18 Skupper vFlow collector controller
2022-12-27T20:16:18.134046769Z 2022/12/27 20:16:18 Version: 1c8cc50
2022-12-27T20:16:18.142111332Z 2022/12/27 20:16:18 Waiting for Skupper router component to start
2022-12-27T20:16:23.155040366Z 2022/12/27 20:16:23 vFlow collector server listing on :8010
2022-12-27T20:16:23.155066026Z 2022/12/27 20:16:23 Starting the Skupper vFlow collector controller
2022-12-27T20:16:26.267318738Z 2022/12/27 20:16:26 Detected event source:  130f4d78-2c47-4220-9b5a-88542d2ac6ee
2022-12-27T20:16:26.958731678Z 2022/12/27 20:16:26 Detected event source:  cefabb27-07b8-462e-a170-1422afd0d571
2022-12-27T20:16:29.191430954Z 2022/12/27 20:16:29 Detected event source:  nmfh7:0
2022-12-27T20:16:31.197371156Z 2022/12/27 20:16:31 Detected event source:  zzgm8:0
2022-12-27T20:16:31.536751356Z panic: runtime error: index out of range [47] with length 47
2022-12-27T20:16:31.536761339Z 
2022-12-27T20:16:31.536763120Z goroutine 42 [running]:
2022-12-27T20:16:31.536764894Z github.com/skupperproject/skupper/pkg/flow.decode(0xc0001936d0)
2022-12-27T20:16:31.536766644Z 	/go/src/app/pkg/flow/encoding.go:204 +0x2f33
2022-12-27T20:16:31.536768411Z github.com/skupperproject/skupper/pkg/flow.(*receiver)._receive(0xc00048a140)
2022-12-27T20:16:31.536770037Z 	/go/src/app/pkg/flow/messaging.go:196 +0x1a5
2022-12-27T20:16:31.536771736Z github.com/skupperproject/skupper/pkg/flow.(*receiver).receive(0xc00048a140)
2022-12-27T20:16:31.536773348Z 	/go/src/app/pkg/flow/messaging.go:168 +0x2f
2022-12-27T20:16:31.536774930Z created by github.com/skupperproject/skupper/pkg/flow.(*receiver).start
2022-12-27T20:16:31.536776557Z 	/go/src/app/pkg/flow/messaging.go:163 +0x5f
```

**Comment by ajssmith** [comment]
fixed in https://github.com/skupperproject/skupper/pull/1009
