### ISSUE TITLE
change to multi port annotation crashes service-controller

### ISSUE THREAD

**Issue by chassing** [skupperproject/skupper#984]
Skupper version: 1.2.0

I have a deployment with a single port annotation, e.g.
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    skupper.io/address: http-foobar
    skupper.io/port: 8080:8080
    skupper.io/proxy: http
```

changing it to multiport, e.g.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    skupper.io/address: http-foobar
    skupper.io/port: 8080:8080,80:8080
    skupper.io/proxy: http
```

crashes the service-controller. It doesn't crash if it's a multiport config from the beginning, just when changing from single to multiport.

this is the service-controller log

```
service-controller E0105 13:05:36.706213       1 runtime.go:78] Observed a panic: runtime.boundsError{x:1, y:1, signed:true, code:0x0} (runtime error: index out of range [1] with length 1)
service-controller goroutine 106 [running]:
service-controller k8s.io/apimachinery/pkg/util/runtime.logPanic({0x13e4620, 0xc00050a318})
service-controller  /go/pkg/mod/k8s.io/apimachinery@v0.17.0/pkg/util/runtime/runtime.go:74 +0x99
service-controller k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x11e05c0})
service-controller  /go/pkg/mod/k8s.io/apimachinery@v0.17.0/pkg/util/runtime/runtime.go:48 +0x75
service-controller panic({0x13e4620, 0xc00050a318})
service-controller  /usr/local/go/src/runtime/panic.go:1038 +0x215
service-controller github.com/skupperproject/skupper/pkg/service.addIngressBridge(0xc00070a180, {0xc000044090, 0x24}, 0xc000886580)
service-controller  /go/src/app/pkg/service/bindings.go:440 +0x725
service-controller github.com/skupperproject/skupper/pkg/service.(*ServiceBindings).updateBridgeConfiguration(0xc00070a180, {0xc000044090, 0x24}, 0xc0001b0c60)
service-controller  /go/src/app/pkg/service/bindings.go:326 +0x5a
service-controller github.com/skupperproject/skupper/pkg/service.RequiredBridges(0x10, {0xc000044090, 0x24})
service-controller  /go/src/app/pkg/service/bindings.go:498 +0x132
service-controller main.(*Controller).updateBridgeConfig(0xc0002e2000, {0xc0004df050, 0x22})
service-controller  /go/src/app/cmd/service-controller/controller.go:497 +0x105
service-controller main.(*Controller).processNextEvent.func1(0xc0002e2000, {0x12cb900, 0xc0003efb60})
service-controller  /go/src/app/cmd/service-controller/controller.go:658 +0x150b
service-controller main.(*Controller).processNextEvent(0xc0002e2000)
service-controller  /go/src/app/cmd/service-controller/controller.go:762 +0x65
service-controller main.(*Controller).runServiceCtrl(...)
service-controller  /go/src/app/cmd/service-controller/controller.go:466
service-controller k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0x0)
service-controller  /go/pkg/mod/k8s.io/apimachinery@v0.17.0/pkg/util/wait/wait.go:152 +0x67
service-controller k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0, 0x3b9aca00, 0x0, 0x1, 0xc00009c660)
service-controller  /go/pkg/mod/k8s.io/apimachinery@v0.17.0/pkg/util/wait/wait.go:153 +0x11d
service-controller k8s.io/apimachinery/pkg/util/wait.Until(0x0, 0x0, 0x0)
service-controller  /go/pkg/mod/k8s.io/apimachinery@v0.17.0/pkg/util/wait/wait.go:88 +0x25
service-controller created by main.(*Controller).Run
service-controller  /go/src/app/cmd/service-controller/controller.go:300 +0x5f7
service-controller panic: runtime error: index out of range [1] with length 1 [recovered]
service-controller  panic: runtime error: index out of range [1] with length 1
service-controller
service-controller goroutine 106 [running]:
service-controller k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x11e05c0})
service-controller  /go/pkg/mod/k8s.io/apimachinery@v0.17.0/pkg/util/runtime/runtime.go:55 +0xd8
service-controller panic({0x13e4620, 0xc00050a318})
service-controller  /usr/local/go/src/runtime/panic.go:1038 +0x215
service-controller github.com/skupperproject/skupper/pkg/service.addIngressBridge(0xc00070a180, {0xc000044090, 0x24}, 0xc000886580)
service-controller  /go/src/app/pkg/service/bindings.go:440 +0x725
service-controller github.com/skupperproject/skupper/pkg/service.(*ServiceBindings).updateBridgeConfiguration(0xc00070a180, {0xc000044090, 0x24}, 0xc0001b0c60)
service-controller  /go/src/app/pkg/service/bindings.go:326 +0x5a
service-controller github.com/skupperproject/skupper/pkg/service.RequiredBridges(0x10, {0xc000044090, 0x24})
service-controller  /go/src/app/pkg/service/bindings.go:498 +0x132
service-controller main.(*Controller).updateBridgeConfig(0xc0002e2000, {0xc0004df050, 0x22})
service-controller  /go/src/app/cmd/service-controller/controller.go:497 +0x105
service-controller main.(*Controller).processNextEvent.func1(0xc0002e2000, {0x12cb900, 0xc0003efb60})
service-controller  /go/src/app/cmd/service-controller/controller.go:658 +0x150b
service-controller main.(*Controller).processNextEvent(0xc0002e2000)
service-controller  /go/src/app/cmd/service-controller/controller.go:762 +0x65
service-controller main.(*Controller).runServiceCtrl(...)
service-controller  /go/src/app/cmd/service-controller/controller.go:466
service-controller k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0x0)
service-controller  /go/pkg/mod/k8s.io/apimachinery@v0.17.0/pkg/util/wait/wait.go:152 +0x67
service-controller k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0, 0x3b9aca00, 0x0, 0x1, 0xc00009c660)
service-controller  /go/pkg/mod/k8s.io/apimachinery@v0.17.0/pkg/util/wait/wait.go:153 +0x11d
service-controller k8s.io/apimachinery/pkg/util/wait.Until(0x0, 0x0, 0x0)
service-controller  /go/pkg/mod/k8s.io/apimachinery@v0.17.0/pkg/util/wait/wait.go:88 +0x25
service-controller created by main.(*Controller).Run
service-controller  /go/src/app/cmd/service-controller/controller.go:300 +0x5f7
```

**Comment by hash-d** [comment]
I was able to reproduce it, as described.  Also, the  `service-controller` does not recover on restart; it keeps crashing and enters `CrashLoopBackOff`.  

Simply restoring the annotation to its old value does not help, either.  In order to take the service-controller out of the crash loop, besides restoring the annotation, one needs to edit the configuration map `skupper-services` on the other namespaces, removing the additional ports (on the `ports` list field).

**Comment by hash-d** [comment]
Instead of moving back, one can move forward with the change, by editing the `skupper-internal` configuration map on all affected namespaces.  There, one needs to duplicate the `listener` block to included the added port.  For example, if the configuration had only

``` 
          [
              "httpListener",
              {
                  "name": "hello-world-frontend:8080",
                  "port": "1024",
                  "address": "hello-world-frontend:8080",
                  "siteId": "fc21e936-f9fe-4ce8-8867-95252f73378b"
              }
          ],
```

one could add 

```
          [
              "httpListener",
              {
                  "name": "hello-world-frontend:80",
                  "port": "1024",
                  "address": "hello-world-frontend:80",
                  "siteId": "fc21e936-f9fe-4ce8-8867-95252f73378b"
              }
          ],
```

right below the previous entry.  

With that change, the `service-controller` comes back up, and the change becomes effective.  It even survives after restarting both `skupper-router` and `service-controller`.  However, as that's a change on the `skupper-internal` configuration map, it's probably not the best option for a production environment.

**Comment by fgiorgetti** [comment]
Alternatively, the service could be removed using the CLI, and considering it is annotated,
once the controller restarts, it will recreate the service with the correct definition.

**Comment by hash-d** [comment]
I have ran the same test against master, and this time it worked fine.  

The stack trace for this issue is exactly the same as the one for #1023 (except for index — 1 vs 2).  However, this may be due to the asynchronous nature of this process: the root cause is different, but they both cause the issue when the system is processing the events they generated.

That, however, I think we'll follow up on on #1023.
